# Generated by Django 4.2.13 on 2024-05-16 23:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DialogMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'User Message'), (2, 'Bot Message')])),
                ('message', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DialogChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('messages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialog.dialogmessage')),
            ],
        ),
    ]
