# Generated by Django 4.2.13 on 2024-05-23 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialogmessage',
            options={'ordering': ('created',)},
        ),
    ]
